# Generated by Django 4.0.5 on 2022-06-13 13:17

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurls',
            name='prefix',
            field=models.CharField(default=client.models.ShortenedUrls.rand_letter, max_length=50),
        ),
    ]
