# Generated by Django 4.0.5 on 2022-06-14 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_shortenedurls_client_shor_prefix_5eb340_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurls',
            name='click',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Staticstic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('web_browser', models.CharField(max_length=50)),
                ('device', models.CharField(choices=[('pc', 'Pc'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=6)),
                ('device_os', models.CharField(max_length=30)),
                ('country_code', models.CharField(default='XX', max_length=2)),
                ('country_name', models.CharField(default='UNKNOWN', max_length=100)),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.shortenedurls')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
